force-app/main/default/objects/uiScreen__c/uiScreen__c.object-meta.xml
<CustomObject>
    <description>Will Display a configurable screen</description>
    <label>UI Screen</label>
    <nameField>
        <label>Screen Api Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UI Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uiScreen__c/fields/BodyParameters__c.field-meta.xml
<CustomField>
    <fullName>BodyParameters__c</fullName>
    <defaultValue>&#39;{}&#39;</defaultValue>
    <description>The component body parameters object</description>
    <inlineHelpText>The component body parameters object</inlineHelpText>
    <label>Body Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uiScreen__c/fields/InnerActionsFilter__c.field-meta.xml
<CustomField>
    <fullName>InnerActionsFilter__c</fullName>
    <description>Will be used to render routes in Magic Wand Menu</description>
    <inlineHelpText>Will be used to render routes in Magic Wand Menu</inlineHelpText>
    <label>Inner Actions Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uiScreen__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <description>The Page or Component Api Name</description>
    <inlineHelpText>The Page or Component Api Name</inlineHelpText>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiScreen__c/fields/ProgressBarType__c.field-meta.xml
<CustomField>
    <fullName>ProgressBarType__c</fullName>
    <description>Will control the style of the progress bar (base or path)</description>
    <inlineHelpText>Will control the style of the progress bar (base or path)</inlineHelpText>
    <label>Progress Bar Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>base</fullName>
                <default>true</default>
                <label>base</label>
            </value>
            <value>
                <fullName>path</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiScreen__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The Type of the container that will displayed</description>
    <inlineHelpText>The Type of the container that will displayed</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>LightningComponent</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiSection__c/uiSection__c.object-meta.xml
<CustomObject>
    <description>Sections will be used as part of a screen to display a process or a grid</description>
    <label>UI Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UI Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uiSection__c/fields/BodyParameters__c.field-meta.xml
<CustomField>
    <fullName>BodyParameters__c</fullName>
    <label>Body Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uiSection__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Order of the Section</description>
    <inlineHelpText>Order of the Section</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uiSection__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <description>The Name of the Visualforce page or component</description>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiSection__c/fields/ParentScreenId__c.field-meta.xml
<CustomField>
    <fullName>ParentScreenId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent screen record Id</description>
    <inlineHelpText>Parent screen record Id</inlineHelpText>
    <label>Parent Screen</label>
    <referenceTo>uiScreen__c</referenceTo>
    <relationshipLabel>UI Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uiSection__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visualforce</fullName>
            </value>
            <value>
                <fullName>LightningComponent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UIScreenController.cls
public with sharing class UIScreenController {

    private static String screenObjectName = 'uiScreen__c';
    private static String screenFields = 'Id,Name,Type__c,PageName__c,InnerActionsFilter__c,ProgressBarType__c,BodyParameters__c';
    private static String sectionObjectName = 'uiSection__c';
    private static String sectionRelatedChild = 'Sections__r';
    private static String sectionFields = 'Id,Name,Title__c,Type__c,PageName__c,BodyParameters__c,ParentScreenId__c,Order__c';
    private static String baseUrl = URL.getSalesforceBaseUrl().getHost();
     /**  
        @MethodName : getScreenByName
        @Description: get Screen Data
    **/
    @AuraEnabled(Cacheable=true)
    public static String getScreenById( String screenId, String contextId)  {
        Map<String,Object> output = new Map<String,Object> ();
        String screenQuery = 'SELECT ' + screenFields + ',( SELECT ' + sectionFields + ' FROM ' + sectionRelatedChild + ' ORDER BY Order__c )' + ' FROM ' + screenObjectName + ' WHERE ';
   
        if( String.isNotBlank(screenId) ) {
            screenQuery += 'Id=\'' + screenId + '\'';
        }
        // if( String.isNotBlank(screenName) ) {
        //     screenQuery += 'Name=\'' + screenName + '\'';
        // }
        screenQuery += ' LIMIT 1';
            System.debug('@@ screenQuery ' + screenQuery);
        uiScreen__c[] screenData = UIUtils.doQuery(screenQuery, 'screenQuery');
        if(screenData.size()>0 && String.isNotBlank(contextId)) {
            String params = screenData[0].BodyParameters__c;
            if(String.isNotBlank(params)) {
                String MergedParams = UIUtils.getMergedURLParameters(params, Id.valueOf(contextId));
                screenData[0].put('BodyParameters__c',MergedParams);
            }
            if(screenData[0].Sections__r.size()>0) {
                for(uiSection__c section : screenData[0].Sections__r) {
                     String sectionParams = section.BodyParameters__c;
                    if(String.isNotBlank(sectionParams)) {
                        String sectionMergedParams = UIUtils.getMergedURLParameters(sectionParams, Id.valueOf(contextId));
                        section.put('BodyParameters__c',sectionMergedParams);
                    }
                }
            }
        }
        output.put('ScreenData',screenData[0]);
        output.put('BaseURL',baseUrl);
        
        return JSON.serialize(output);
    }
}