force-app/main/default/objects/uiRouteAction__c/uiRouteAction__c.object-meta.xml
<CustomObject>
    <label>UI Route Action</label>
    <nameField>
        <label>Route Api Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UI Route Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uiRouteAction__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Only Active will be displayed</description>
    <inlineHelpText>Only Active will be displayed</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/ContextIdField__c.field-meta.xml
<CustomField>
    <fullName>ContextIdField__c</fullName>
    <defaultValue>&#39;Id&#39;</defaultValue>
    <description>Which Field to use from current Context Object as a Context Id</description>
    <inlineHelpText>Which Field to use from current Context Object as a Context Id</inlineHelpText>
    <label>ContextId Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/FilterName__c.field-meta.xml
<CustomField>
    <fullName>FilterName__c</fullName>
    <defaultValue>&#39;Recent&#39;</defaultValue>
    <description>The ListView Name</description>
    <inlineHelpText>The ListView Name</inlineHelpText>
    <label>Filter Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/IsNavigation__c.field-meta.xml
<CustomField>
    <fullName>IsNavigation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will enable navigation between app pages</description>
    <inlineHelpText>Will enable navigation between app pages</inlineHelpText>
    <label>Navigation Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The displayed Label on component</description>
    <inlineHelpText>The displayed Label on component</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/LightningIcon__c.field-meta.xml
<CustomField>
    <fullName>LightningIcon__c</fullName>
    <defaultValue>&#39;standard:account&#39;</defaultValue>
    <description>select SLDS Icon to display</description>
    <inlineHelpText>select SLDS Icon to display</inlineHelpText>
    <label>Lightning Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/MergedParameters__c.field-meta.xml
<CustomField>
    <fullName>MergedParameters__c</fullName>
    <description>The %String% will be replaced with Merged Values from Context Object</description>
    <inlineHelpText>The %String% will be replaced with Merged Values from Context Object</inlineHelpText>
    <label>Merged Parameters</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>view</fullName>
                <default>true</default>
                <label>view</label>
            </value>
            <value>
                <fullName>edit</fullName>
            </value>
            <value>
                <fullName>clone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/NavigationType__c.field-meta.xml
<CustomField>
    <fullName>NavigationType__c</fullName>
    <description>The Type of Navigation from component</description>
    <inlineHelpText>The Type of Navigation from component</inlineHelpText>
    <label>Navigation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WebPage</fullName>
                <default>true</default>
                <label>Web Page</label>
            </value>
            <value>
                <fullName>ListView</fullName>
                <label>List View</label>
            </value>
            <value>
                <fullName>RecordHome</fullName>
                <label>Record Home</label>
            </value>
            <value>
                <fullName>LightningPage</fullName>
                <label>Lightning Page</label>
            </value>
            <value>
                <fullName>RelatedList</fullName>
                <label>Related List</label>
            </value>
            <value>
                <fullName>RecordPage</fullName>
                <label>Record Page</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <description>The Target sObject for Navigation or Context Object when a Related List</description>
    <inlineHelpText>The Target sObject for Navigation or Context Object when a Related List</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>uiRouteAction__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Order of display</description>
    <inlineHelpText>The Order of display</inlineHelpText>
    <label>Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <description>Visualforce or Component Name</description>
    <inlineHelpText>Visualforce or Component Name</inlineHelpText>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/RelationshipApiName__c.field-meta.xml
<CustomField>
    <fullName>RelationshipApiName__c</fullName>
    <description>The RelationshipName of The Related List</description>
    <inlineHelpText>The RelationshipName of The Related List</inlineHelpText>
    <label>Relationship Api Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contacts</fullName>
            </value>
            <value>
                <fullName>ChildAccounts</fullName>
            </value>
            <value>
                <fullName>Cases</fullName>
            </value>
            <value>
                <fullName>Opportunities</fullName>
            </value>
            <value>
                <fullName>CombinedAttachments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/TargetURL__c.field-meta.xml
<CustomField>
    <fullName>TargetURL__c</fullName>
    <description>The webpage URL of the page you are navigating to.</description>
    <inlineHelpText>The webpage URL of the page you are navigating to.</inlineHelpText>
    <label>TargetURL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/uiRouteAction__c/fields/uiScreenId__c.field-meta.xml
<CustomField>
    <fullName>uiScreenId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Screen that will be displayed when clicked</description>
    <inlineHelpText>The Screen that will be displayed when clicked</inlineHelpText>
    <label>UI Screen</label>
    <referenceTo>uiScreen__c</referenceTo>
    <relationshipLabel>UI Route Actions</relationshipLabel>
    <relationshipName>RouteActions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UIActionRoutesController.cls
public with sharing class UIActionRoutesController {
    
    private static String routeObjectName = 'UIRouteAction__c';
    private static String groupingFieldName = 'Group__c';
    private static String orderField = 'Order__c';
    private static String[] routeFields = new List<String>{'Id','Name','uiScreenId__c','ContextIdField__c','Label__c','Group__c','LightningIcon__c','NavigationType__c','RelationshipApiName__c','FilterName__c','Mode__c','ObjectApiName__c','IsNavigation__c','TargetURL__c','MergedParameters__c','Active__c','PageName__c'};
    private static String routeStaticFilterClause = 'Active__c = true';
    private static Integer routeStaticLimit = 50;
    /**  
        @MethodName : getFieldSetFromObjectId
        @Description: get all fields from a Fieldset Name and contextId 
    **/
    @AuraEnabled(Cacheable=true)
    public static String getGroupedRoutesList( String contextId, String contextObject, String extraWhereClause,String sortOrder )  {
        Set<String> groupNames = new Set<String>();
        String routeWhereClause = routeStaticFilterClause;
        if(String.isNotBlank(extraWhereClause)) {
            routeWhereClause += ' AND ' + extraWhereClause;
        }
        String routeSortClause = orderField + ' ' + sortOrder;
        String routeQueryString = UIUtils.buildSOQLQuery(routeFields,routeObjectName, routeWhereClause,routeSortClause,routeStaticLimit);
        List<Sobject> routesList = UIUtils.doQuery(routeQueryString,'routeQueryString');
        List<Sobject> updatedRoutesList = new List<Sobject>();
        for(Sobject route:routesList) {
            String URLParams = (String)route.get('MergedParameters__c');

            if(contextId !='home'){
            String contextField = (String)route.get('ContextIdField__c');
            //call Merged ContextId Method
                if(contextField == 'Id' || String.isBlank(contextField)) {
                    route.put('ContextIdField__c',contextId);
                }
                else {
                    try {
                        String returnedContext = getContextId(contextField,contextObject,contextId);
                        route.put('ContextIdField__c',returnedContext);
                    }
                    catch(Exception e) {
                        throw new AuraHandledException( 'Wrong Field ' + e.getMessage() ); 
                    }
                }
           
            
            //call Merged URL Method
            if(String.isNotBlank(URLParams)){
            String MergedURLParams = UIUtils.getMergedURLParameters(URLParams,contextId);
            route.put('MergedParameters__c',MergedURLParams);
            }
            }
            String currentGroup = (String)route.get(groupingFieldName);
            groupNames.add(currentGroup);
            updatedRoutesList.add(route);
        }
        
        List<Map<String,Object>> groupedRoutesList = new List<Map<String,Object>> ();
        for(String  groupName: groupNames)  {
          Map<String,Object> groupObject = new Map<String,Object>();
          List<SObject>groupRoutes = new List<SObject>();
          for(Sobject route:updatedRoutesList) {
              String currentRouteGroup = (String)route.get(groupingFieldName);
              if( currentRouteGroup == groupName ) {
                  groupRoutes.add(route);
              }
          }
          groupObject.put('groupName',groupName);
          groupObject.put('routes',groupRoutes);
          groupedRoutesList.add(groupObject);   
        }
        return JSON.serialize(groupedRoutesList);
    }
    /**  
        @MethodName : getContextIdField
        @Description: Will Merge Context sObject values into DataService Request URL parameters
    **/
    public static String getContextId(String contextField, String contextObjectName, Id contextId) {
        String contextQuery = 'SELECT ' + contextField + ' FROM ' + contextObjectName + ' WHERE Id=\'' + contextId +'\'';
        System.debug('contextQuery ' + contextQuery);
        List<Sobject> contextSObjects = UIUtils.doQuery(contextQuery,'contextQuery');
        return String.valueOf(contextSObjects[0].get(contextField));
    }
    
   
}